<?xml version="1.0"?>
<package format="3">
  <name>ros2_basics</name>
  <version>0.1.0</version>
  <description>ROS 2 talker-listener beginner demo</description>
  <maintainer email="sannyuntwin21@gmail.com">Sanny</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>example_interfaces</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>

  <buildtool_depend>rosidl_default_generators</buildtool_depend>
  <depend>action_msgs</depend>
  <member_of_group>rosidl_interface_packages</member_of_group>

</package>
